# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bkd705
email: brennenkdenomme@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documenting a teenagers journey through the depths of self taught programming and programming in college.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bkd705.github.io" # the base hostname & protocol for your site
twitter_username: bkd705
github_username:  bkd705

# Build settings
markdown: kramdown
