###########
# site.title

title:    'brennen denomme'
subtitle: 'compsci student & javascript aficionado'


nav:
- { title: 'Welcome',              href: '/' }
- { title: 'Blog',                 href: '/blog.html' }


#########################
# more settings

markdown: kramdown
permalink: /:year/:slug

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

